# .gitlab-ci.yml
stages:
  - build
  - deploy

variables:
  # GitLab Container Registry URL
  REGISTRY_URL: $CI_REGISTRY
  IMAGE_NAME: $CI_REGISTRY_IMAGE/planar-waves
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  # Docker-in-Docker settings
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

# Build Docker image
build:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:24.0.7-dind
      alias: docker
  before_script:
    # Wait for Docker to be ready
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - main
    - master
    - development

# Generate Kubernetes manifest
generate-manifest:
  stage: deploy
  image: alpine:latest
  before_script:
    - mkdir -p k8s
  script:
    - |
      cat > k8s/planar-waves-job.yaml << EOF
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: planar-waves-${CI_COMMIT_SHORT_SHA}
        namespace: braingeneers  # TODO: Replace with your actual namespace
      spec:
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: planar-waves
              image: ${IMAGE_NAME}:${IMAGE_TAG}
              imagePullPolicy: Always
              command:
              - /bin/bash
              - -c
              - |
                # Set environment variables
                export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
                export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
                export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32
                
                # Run the analysis
                cd /workspace
                python /workspace/src/runner.py \\
                  --s3-input-path s3://braingeneers/personal/dani/sample_2/ \\
                  --s3-output-path s3://braingeneers/personal/dani/sample_2_output/
              resources:
                requests:
                  cpu: "4"
                  memory: "16Gi"
                  nvidia.com/gpu: 1
                limits:
                  cpu: "8"
                  memory: "32Gi"
                  nvidia.com/gpu: 1
              volumeMounts:
              - name: output-volume
                mountPath: /workspace/output
              - name: prp-s3-credentials
                mountPath: "/root/.aws/credentials"
                subPath: "credentials"
              - name: shm-volume
                mountPath: /dev/shm
            tolerations:
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "PreferNoSchedule"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: nvidia.com/gpu.product
                      operator: In
                      values:
                      - NVIDIA-A10
                      - NVIDIA-GeForce-RTX-3090
            restartPolicy: Never
            imagePullSecrets:
            - name: gitlab-registry
            volumes:
            - name: output-volume
              persistentVolumeClaim:
                claimName: planar-waves-output-pvc
            - name: prp-s3-credentials
              secret:
                secretName: prp-s3-credentials
                defaultMode: 256
            - name: shm-volume
              emptyDir:
                medium: Memory
                sizeLimit: 8Gi
      EOF
    - echo "Kubernetes manifest generated with image: ${IMAGE_NAME}:${IMAGE_TAG}"
    - cat k8s/planar-waves-job.yaml | head -20  # Debug: show first 20 lines
  artifacts:
    paths:
      - k8s/planar-waves-job.yaml
    expire_in: 1 week
  only:
    - main
    - master